name: Tests (PHP)

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Install NPM Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run production

      - name: Run tests
        run: ./vendor/bin/phpunit
